services:
  python:
    build: 
      context: ./python-api
      no_cache: true     # <-- Esto fuerza a Docker a ignorar la caché al compilar este servicio
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - my-net

  postgres:
    image: postgres:16
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_CATALOG}
    expose:
      - ${DATABASE_PORT}
    networks:
      - my-net
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  my-net:

volumes:
  pgdata: